console.log(`      |      |      `)
console.log(`  ${"x"}   |   ${"o"}  |   ${"x"}   `)
console.log(`      |      |      `)
console.log(`--------------------`)
console.log(`      |      |      `)
console.log(`  ${"o"}   |   ${"x"}  |  ${"x"}   `)
console.log(`      |      |      `)
console.log(`--------------------`)
console.log(`      |      |      `)
console.log(`  ${"x"}   |   ${"o"}  |   ${"x"}    `)
console.log(`      |      |      `)